server:
  port: 8091

spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/gis?serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
  application:
      name: admin-server
  boot:
      admin:
        client:
          url: http://localhost:9301

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always


mybatis:
  mapper-locations: classpath*:com/system/mapper/*.xml
  type-aliases-package: com.system.entity

mapper:
    mappers: com.system.dao.BaseDao
    not-empty: false
    identity: MYSQL

pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql

#showSql
logging:
  level:
    com:
      system:
        dao : debug
  file: admin-client.log